/**
 * Americano: a social format where partners rotate every round.
 *
 * Unlike every other draw in this app, the entrants are INDIVIDUALS but the
 * matches are 2 v 2 — so a match has four people in it, and the pairings change
 * from round to round. Nobody is knocked out and there is no bracket: the
 * winner is whoever has personally scored the most points by the end.
 *
 * The schedule is what makes or breaks the evening. Two rules matter to the
 * people on court, in this order:
 *
 *   1. Play with as many different partners as possible.
 *   2. Play against as many different opponents as possible.
 *
 * Rule 1 is solved exactly rather than approximately. The partnerships are
 * generated by the circle method — the same rotation used to build a round
 * robin fixture list — which produces a *1-factorization* of the complete
 * graph: a set of rounds in which every player is paired exactly once per
 * round and no pairing is ever repeated. So for any run up to the natural
 * length of the format, no two people are ever made to partner twice. (A
 * greedy "pick the least-used partner" pass looks reasonable but strands the
 * last four players of a round with a repeat they cannot avoid, which is
 * exactly the thing players notice.)
 *
 * Rule 2 is then greedy over those fixed pairs, and rest is shared by playing
 * whoever has sat out most. Everything is deterministic, so the schedule an
 * organiser previews is the one they get.
 */

export interface AmericanoMatch {
  round: number; // 1-based
  posIndex: number; // position within the round
  team1: [number, number]; // indexes into the player list
  team2: [number, number];
}

export interface AmericanoSchedule {
  matches: AmericanoMatch[];
  /** Who sits out each round, when the player count is not a multiple of four. */
  sitOuts: number[][];
}

export const MIN_AMERICANO_PLAYERS = 4;
export const MAX_AMERICANO_PLAYERS = 32;
export const MAX_AMERICANO_ROUNDS = 20;

/** Players actually on court in a round — the rest sit out, four to a match. */
export function playersPerRound(playerCount: number): number {
  return playerCount - (playerCount % 4);
}

export function matchesPerRound(playerCount: number): number {
  return Math.floor(playerCount / 4);
}

/**
 * A sensible default number of rounds.
 *
 * Partnering everyone exactly once takes playerCount-1 rounds, which is the
 * natural "full" americano — but for a large group that is a very long night,
 * so it is capped at something a social session actually finishes.
 */
export function defaultRounds(playerCount: number): number {
  return Math.max(1, Math.min(playerCount - 1, 8));
}

/** Symmetric pair counter, keyed on the lower index first. */
class PairCount {
  private readonly n: number;
  private readonly data: number[];
  constructor(n: number) {
    this.n = n;
    this.data = new Array(n * n).fill(0);
  }
  get(a: number, b: number): number {
    return this.data[a * this.n + b];
  }
  bump(a: number, b: number) {
    this.data[a * this.n + b] += 1;
    this.data[b * this.n + a] += 1;
  }
}

/**
 * The circle method: one round's worth of partnerships.
 *
 * Player 0 stays put while everyone else rotates around them; each round then
 * pairs the two ends of the line inwards. Over `size - 1` rounds this visits
 * every possible pairing exactly once. An odd player count is handled by
 * rotating a ghost player through the field — whoever draws the ghost sits out,
 * which spreads the byes evenly for free.
 *
 * Exported because the team americano rotates partnerships inside each team the
 * same way.
 */
export function circlePairs(size: number, round: number): [number, number][] {
  const rest = [...Array(size - 1).keys()].map((i) => i + 1);
  const shift = round % (size - 1);
  const rotated = [...rest.slice(shift), ...rest.slice(0, shift)];
  const line = [0, ...rotated];
  const pairs: [number, number][] = [];
  for (let i = 0; i < size / 2; i++) pairs.push([line[i], line[size - 1 - i]]);
  return pairs;
}

export function generateAmericano(playerCount: number, rounds: number): AmericanoSchedule {
  if (!Number.isInteger(playerCount) || playerCount < MIN_AMERICANO_PLAYERS) {
    throw new Error(`Americano needs at least ${MIN_AMERICANO_PLAYERS} players, got ${playerCount}`);
  }
  if (playerCount > MAX_AMERICANO_PLAYERS) {
    throw new Error(`Americano supports up to ${MAX_AMERICANO_PLAYERS} players, got ${playerCount}`);
  }
  const roundCount = Math.max(1, Math.min(Math.floor(rounds), MAX_AMERICANO_ROUNDS));

  // An odd field rotates a ghost player; whoever is paired with it sits out.
  const ghost = playerCount % 2 === 1 ? playerCount : -1;
  const circleSize = ghost >= 0 ? playerCount + 1 : playerCount;

  const opponent = new PairCount(playerCount);
  const played = new Array(playerCount).fill(0);
  const rested = new Array(playerCount).fill(0);

  const matches: AmericanoMatch[] = [];
  const sitOuts: number[][] = [];
  const wanted = matchesPerRound(playerCount) * 2; // pairs needed to fill the courts

  // With an odd field the rotation decides in advance who draws the ghost, and
  // therefore who is forced to sit, in every round of the night. Those byes are
  // counted up front so the choices below can see them coming: a player with a
  // forced bye still ahead of them has effectively already been rested, and
  // benching them again now is how someone ends up sitting out four times while
  // somebody else sits once.
  const ghostSitterOf: (number | undefined)[] = [];
  const pendingForced = new Array(playerCount).fill(0);
  for (let round = 1; round <= roundCount; round++) {
    const bye = circlePairs(circleSize, round - 1).find(([a, b]) => a === ghost || b === ghost);
    const sitter = bye?.find((p) => p !== ghost);
    ghostSitterOf[round] = sitter;
    if (sitter !== undefined) pendingForced[sitter] += 1;
  }

  for (let round = 1; round <= roundCount; round++) {
    const all = circlePairs(circleSize, round - 1);
    const pairs = all.filter(([a, b]) => a !== ghost && b !== ghost) as [number, number][];

    // This round's forced bye is no longer in the future: bank it as real rest
    // before anything else is decided.
    const ghostSitter = ghostSitterOf[round];
    if (ghostSitter !== undefined) {
      rested[ghostSitter] += 1;
      pendingForced[ghostSitter] -= 1;
    }
    const effectiveRest = (p: number) => rested[p] + pendingForced[p];

    // When the pairs don't divide evenly into matches, some must sit. Play the
    // pairs whose members have rested most, so the byes go round the group.
    //
    // Sitting a pair adds a bye to both its members, so the pair to bench is
    // the one whose members have the fewest byes between them — the pair total
    // is exactly the quantity that keeps the distribution level. Ranking on one
    // member instead, by either extreme, quietly excludes people: judged by its
    // best-rested member, the pair containing the circle's fixed player wins
    // every tie and that player is never benched at all.
    //
    // Level pairs are then separated by who has PLAYED most, which is the same
    // fairness question asked from the other side. It has to be a real signal
    // rather than something arbitrary like the lower index: the circle puts one
    // player in every round, so any fixed ordering silently favours them.
    const sitKey = (p: [number, number]) => [
      effectiveRest(p[0]) + effectiveRest(p[1]),
      Math.max(effectiveRest(p[0]), effectiveRest(p[1])),
      -(played[p[0]] + played[p[1]]),
      p[0],
    ];
    // Ascending: the pairs most deserving of a bye come first.
    const ordered = [...pairs].sort((x, y) => (less(sitKey(x), sitKey(y)) ? -1 : 1));
    const sitCount = pairs.length - wanted;
    const benched = ordered.slice(0, sitCount).flat();
    const playing = ordered.slice(sitCount);
    for (const p of benched) rested[p] += 1;
    sitOuts.push([...benched, ...(ghostSitter !== undefined ? [ghostSitter] : [])].sort((a, b) => a - b));

    // Pair the teams off into matches, preferring opponents who have met least.
    const pool = [...playing];
    let posIndex = 0;
    while (pool.length >= 2) {
      const team1 = pool.shift()!;
      let bestIdx = 0;
      let bestScore: number[] | null = null;
      for (let i = 0; i < pool.length; i++) {
        const t = pool[i];
        const meetings =
          opponent.get(team1[0], t[0]) +
          opponent.get(team1[0], t[1]) +
          opponent.get(team1[1], t[0]) +
          opponent.get(team1[1], t[1]);
        const score = [meetings, played[t[0]] + played[t[1]], i];
        if (bestScore === null || less(score, bestScore)) {
          bestScore = score;
          bestIdx = i;
        }
      }
      const team2 = pool.splice(bestIdx, 1)[0];

      for (const x of team1) for (const y of team2) opponent.bump(x, y);
      for (const p of [...team1, ...team2]) played[p] += 1;

      matches.push({ round, posIndex, team1, team2 });
      posIndex++;
    }
  }

  return { matches, sitOuts };
}

/** Lexicographic compare of two score tuples. */
function less(a: number[], b: number[]): boolean {
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return a[i] < b[i];
  }
  return false;
}


/** How varied a schedule actually turned out — shown to the organiser before they commit. */
export function scheduleQuality(schedule: AmericanoSchedule, playerCount: number) {
  const partner = new PairCount(playerCount);
  const played = new Array(playerCount).fill(0);
  for (const m of schedule.matches) {
    partner.bump(m.team1[0], m.team1[1]);
    partner.bump(m.team2[0], m.team2[1]);
    for (const p of [...m.team1, ...m.team2]) played[p] += 1;
  }
  let repeatedPartnerships = 0;
  let distinctPartners = 0;
  for (let a = 0; a < playerCount; a++) {
    for (let b = a + 1; b < playerCount; b++) {
      const c = partner.get(a, b);
      if (c > 0) distinctPartners++;
      if (c > 1) repeatedPartnerships += c - 1;
    }
  }
  return {
    repeatedPartnerships,
    distinctPartners,
    minMatches: Math.min(...played),
    maxMatches: Math.max(...played),
  };
}
