/**
 * Standard single-elimination seed placement for a 16-player draw.
 *
 * `seedSlots(16)` returns, for each of the 16 draw positions (top -> bottom),
 * which seed number belongs there. It's generated by the classic recursive
 * "fold" so that the top seeds are spread across separate quarters: seeds 1 & 2
 * can only meet in the final, and seeds 1-4 each land in a different quarter, so
 * they only meet from the semifinals onward.
 *
 * For the compass draw the East Round of 16 is paired input[0] v input[1],
 * input[2] v input[3], ... so the returned slot order IS the input order the
 * seeder expects.
 */
export function seedSlots(n: number): number[] {
  let seeds = [1, 2];
  while (seeds.length < n) {
    const sum = seeds.length * 2 + 1;
    const next: number[] = [];
    for (const s of seeds) {
      next.push(s);
      next.push(sum - s);
    }
    seeds = next;
  }
  return seeds;
}

export interface SeedEntry {
  name: string;
  /** 1-based seed. Lower = stronger. Undefined/0 = unseeded. */
  seed?: number | null;
}

/**
 * Arranges 16 entries into draw-slot order. Seeded players are placed at the
 * standard bracket position for their EXACT seed number (1..16); unseeded
 * players fill the remaining slots in the order given. Returns the 16 names in
 * slot order, ready to hand to seedTournament().
 *
 * Honouring the exact seed number (not a compressed rank) matters: with pros
 * seeded 1-4 and beginners seeded 13-16, seed 1 lands opposite seed 16, seed 4
 * opposite seed 13, etc. — so each top seed draws a bottom seed in Round 1, and
 * the top seeds still only meet from the semifinals onward.
 */
export function arrangeDraw(entries: SeedEntry[]): string[] {
  if (entries.length !== 16) {
    throw new Error(`Draw requires exactly 16 players, got ${entries.length}`);
  }

  const slotForSeed = seedSlots(16); // slotForSeed[slotIndex] = seed number (1..16) for that draw position

  const seedToName = new Map<number, string>();
  for (const e of entries) {
    if (e.seed != null && e.seed > 0) {
      if (e.seed > 16) throw new Error(`Seed ${e.seed} is out of range (1-16)`);
      if (seedToName.has(e.seed)) throw new Error(`Two players share seed ${e.seed}`);
      seedToName.set(e.seed, e.name);
    }
  }
  const unseeded = entries.filter((e) => e.seed == null || e.seed <= 0).map((e) => e.name);

  const slots: (string | null)[] = new Array(16).fill(null);
  for (let slotIndex = 0; slotIndex < 16; slotIndex++) {
    const seedNo = slotForSeed[slotIndex];
    const name = seedToName.get(seedNo);
    if (name) slots[slotIndex] = name;
  }
  let u = 0;
  for (let slotIndex = 0; slotIndex < 16; slotIndex++) {
    if (slots[slotIndex] === null) slots[slotIndex] = unseeded[u++] ?? "";
  }

  return slots as string[];
}
